name: 'Setup Environment'
description: 'Setup the CI environment for use'
outputs:
  runner:
    description: "Which environment the action should target"
runs:
  using: composite
  steps:
    - name: "Setup the environment"
      run: |
        if [ ${{ github.ref }} == 'refs/heads/main' ]; then
          echo "::set-output name=runner::ubuntu-latest"
        else
          echo "::set-output name=runner::macos-latest"
        fi
