# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_call:

jobs:
  setup:
    runs-on: [ubuntu-latest]
    outputs:
      runner: ${{ steps.setup.outputs.runner }}
    steps:
      - uses: 1ng3n/init-ci@main
        id: setup
